### ISSUE TITLE
Why is plugins/user-switching in the .gitignore file?

### ISSUE THREAD

**Issue by jonathanstegall** [Automattic/vip-go-skeleton#33]
Could someone speak to this one? I can see that query-monitor is here because it is already in the /wp-content/mu-plugins folder, but user-switching, log-deprecated-notices, and monster-widget are not. For my own purposes, I was trying to add user-switching to my repo.

Will there be problems if I remove this from my own repo's .gitignore file?

**Comment by mjangda** [comment]
It's a holdover from a long time ago (https://github.com/Automattic/vip-go-skeleton/pull/4). Should be safe to remove in your repo. We'll also update the list.

**Comment by jonathanstegall** [comment]
HI for what it's worth, I've noticed a possible reason for this plugin being disabled. When I use it along with Co-Authors-Plus, it causes errors on author archive pages. I've only seen the errors on those author archives so far, although it's possible it also causes them in other places.

```
Fatal error: Uncaught TypeError: Argument 1 passed to user_switching::switch_to_url() must be an instance of WP_User, instance of stdClass given, called in /var/www/wp-content/plugins/user-switching/user-switching.php on line 486 and defined in /var/www/wp-content/plugins/user-switching/user-switching.php:696 Stack trace: #0 /var/www/wp-content/plugins/user-switching/user-switching.php(486): user_switching::switch_to_url(Object(stdClass)) #1 /var/www/wp-includes/class-wp-hook.php(286): user_switching->action_admin_bar_menu(Object(WP_Admin_Bar)) #2 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /var/www/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #4 /var/www/wp-includes/admin-bar.php(83): do_action_ref_array('admin_bar_menu', Array) #5 /var/www/wp-includes/class-wp-hook.php(286): wp_admin_bar_render('') #6 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #7 /var/www/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #8 /var/www/wp-includes/general-template.php(2630): do_action('wp_footer') #9 /var/www/wp-content/themes/minnpost-largo/footer.php(65): wp_footer() #10 /var/www/wp-includes/template.php(688): require_once('/var/www/wp-con...') #11 /var/www/wp-includes/template.php(647): load_template('/var/www/wp-con...', true) #12 /var/www/wp-includes/general-template.php(76): locate_template(Array, true) #13 /var/www/wp-content/themes/minnpost-largo/archive.php(171): get_footer() #14 /var/www/wp-includes/template-loader.php(74): include('/var/www/wp-con...') #15 /var/www/wp-blog-header.php(19): require_once('/var/www/wp-inc...') #16 /var/www/index.php(17): require('/var/www/wp-blo...') #17 {main} thrown in /var/www/wp-content/plugins/user-switching/user-switching.php on line 696
```

In any case I'm disabling it for now, but I wanted to mention in case that is why it was initially ignored.
